* leanStats Project

** Description
This is the leanStats project, which computes lean metrics on ticket data.

** Prerequisites
- Python 3.x
- pipenv

** Setting Up

*** Clone the Repository
#+BEGIN_SRC bash
git clone git@github.com:fimblo/leanStats.git
cd leanStats
#+END_SRC

*** Set Up the Python Environment with pipenv

To manage dependencies and virtual environments, we use `pipenv`.

If you haven't installed pipenv yet, you can do so with pip:

#+BEGIN_SRC bash
pip install pipenv
#+END_SRC

Now, set up the environment for this project:

#+BEGIN_SRC bash
pipenv install
#+END_SRC

This command will create a virtual environment and install all
dependencies listed in the `Pipfile`.

** Running leanStats

With everything set up, you can run leanStats using:

#+BEGIN_SRC bash
pipenv run leanStats -i sample.csv
#+END_SRC

This will output something like:
#+begin_example
$ pipenv run leanStats -i data/sample.csv 
Loading .env environment variables...
Key|timestamp_start|timestamp_end|cycletime|median_cycletime|p85_cycletime|throughput
PROJ-004|2023-08-07 11:23:54|2023-08-07 11:23:58|1|1|1|1
PROJ-002|2023-08-09 07:38:10|2023-08-09 12:03:24|1|1|1|2
PROJ-003|2023-08-07 10:46:48|2023-08-09 14:09:05|3|1|3|3
PROJ-001|2023-08-15 06:39:14|2023-08-20 07:39:21|6|6|6|1
#+end_example

Not pretty, but it's a work in progress :)

** Testing

Explain how to run tests here (if you have them). For example:

#+BEGIN_SRC bash
pipenv run test
#+END_SRC

** Contributing

If you'd like to contribute, please fork the repository and make
changes as you'd like. Pull requests are warmly welcome.

** License
This project is licensed under the GNU General Public License v3.0 -
see the LICENSE file for details.
