name: "Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install
        echo 'PYTHONPATH=src:$PYTHONPATH' > .env

    - name: Run tests
      run: pipenv run test
